### ISSUE TITLE
Stuck at getPlaylistById

### ISSUE THREAD

**Issue by marcguillemdev** [projectgoav/E.Deezer#70]
I am trying to get the Top 100 songs from each country by indicating the playlist ID like this:

public async void retrieve_playlist(uint id_playlist)
        {
            var dez = DeezerSession.CreateNew();
            var po = await dez.Browse.GetPlaylistById(id_playlist);
            var tracks_po = po.GetTracks();

            for(int i = 0; i < tracks_po.Result.Count(); i++)
            {
                listBox2.Items.Add(tracks_po.Result.ElementAt(i).Title + " de " + tracks_po.Result.ElementAt(i).Artist.Name);
            }
        }

The invocation is this:

`retrieve_playlist(716146082);`

But the result is this:

> System.NullReferenceException: 'Referencia a objeto no establecida como instancia de un objeto.'

![erro2](https://user-images.githubusercontent.com/30577118/61887076-2f9a9a00-af01-11e9-99c7-80bd9fc54fd8.PNG)
![error1](https://user-images.githubusercontent.com/30577118/61887077-2f9a9a00-af01-11e9-9ae6-16ddae5e068b.PNG)

Thanks in advance

**Comment by projectgoav** [comment]
Can you send me a copy of the full stack trace from the exception please

**Comment by marcguillemdev** [comment]
> Can you send me a copy of the full stack trace from the exception please

Of course, here is it.

>   | StackTrace | "   en DeezerApi.Form1.<retrieve_playlist>d__41.MoveNext() en C:\\Users\\marc9\\source\\repos\\DeezerApi\\DeezerApi\\Form1.cs:línea 728" | string

**Comment by projectgoav** [comment]
According to the API explorer the playlist doesn't exist. 

This library should be throwing an exception telling you this so I'll look into that! Your code should be handling exceptions or `null` returns which should mitigate this issue until I can get the exception throwing fixed.

**Comment by DanixPC** [comment]
Its stranger because the ID of playlist its from here: 

> deezer.com/en/playlist/1116190041

Is the top 100 Spain provided by deezer

**Comment by marcguillemdev** [comment]
Oops, you are right, that playlist doesn't exist. I tried with this and still don't work.

> 1362510315

[https://www.deezer.com/en/playlist/1362510315](url)

**Comment by projectgoav** [comment]
The json parsing code was missing a custom converter meaning that objects fetched by their ID wasn't working. 

#71 fixes this and will be released to Nuget shortly after I post this :)
