### ISSUE TITLE
Getting this error when im searching album name

### ISSUE THREAD

**Issue by marcguillemdev** [projectgoav/E.Deezer#79]
Hi! I'm having a problem when I look for albums using this api:

```
var deezer = DeezerSession.CreateNew();
var answer = await deezer.Search.Albums(album_texto.Text, aCount: resultados); <-- HERE
```

InnerException:

> 

  | Nombre | Valor | Tipo
-- | -- | -- | --
▶ | InnerException | {"Error converting value -1 to type 'System.UInt32'. Path 'data[7].genre_id', line 1, position 10930."} | System.Exception {Newtonsoft.Json.JsonSerializationException}

Stack Trace:

>    en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en System.Threading.Tasks.Task`1.get_Result()
   en E.Deezer.Endpoint.SearchEndpoint.<Get>b__10_0[TSource,TDest](Task`1 aTask)
   en System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Guzer.Form1.<buscar_album>d__53.MoveNext() en C:\Users\marc9\source\repos\Guzer\Guzer\Form1.cs:línea 930

This error not happens if i search by Artist name, but if i search by Album name i have this.

**Comment by projectgoav** [comment]
Thanks for reporting this. I thought it should have been fixed already but maybe I've not pushed this to Nuget...

Can you give me a copy of the name you are searching with please? I'll add a test to make sure this doesn't happen again.

**Comment by marcguillemdev** [comment]
> Thanks for reporting this. I thought it should have been fixed already but maybe I've not pushed this to Nuget...
> 
> Can you give me a copy of the name you are searching with please? I'll add a test to make sure this doesn't happen again.

Of course, the text is Impronta. Its an album from Lori Meyers. I tried with some names and i had the same result. But i tried with The lion across the field and it worked perfectly. Its strange.

**Comment by projectgoav** [comment]
Yep, I have fixed this but just not released it to Nuget. It's up now as v4.2.1 :)
