### ISSUE TITLE
Error when create new playlist

### ISSUE THREAD

**Issue by ghost** [projectgoav/E.Deezer#80]
Hi, 
When i attempt to create no playlist i receive this errors : 
1. AggregateException : One or more errors occurred.
2. JsonSerializationException : Error converting value 6746872064 to type 'System.UInt32'. Path 'id', line 1, position 16.
3. OverflowException : Value was either too large or too small for a UInt32.

Playlist is created successfully but it's return error !

**Comment by projectgoav** [comment]
Thanks for reporting this. I'll look into this and try to get a fix out in the next couple of days

**Comment by projectgoav** [comment]
Fixed in #81 

Will publish a release later this evening :)
