### ISSUE TITLE
playlist id longer than uint

### ISSUE THREAD

**Issue by poirier-benoit** [projectgoav/E.Deezer#96]
Trying to use GetPlaylistById() and some playlist id are larger than uint32 range, by a lot.
for example, the following public playlist: [(https://api.deezer.com/playlist/7371445944/)](https://api.deezer.com/playlist/7371445944/)

**Comment by projectgoav** [comment]
Can you tell me what version of the library you are using from Nuget (or if you are building locally?)

From what I can see in the code, all the playlist endpoints accept `ulong` as their argument that should be more than plenty to cover this.

**Comment by poirier-benoit** [comment]
Using 4.2.2 from NuGet in Visual Studio 2022 Community.
Line of code is simply: `var deezerPlaylist = await deezer.Browse.GetPlaylistById(deezerPlaylistId);`

**Comment by projectgoav** [comment]
If you update to 5.0.0-beta1 do you still experience the problem? 

You might need to opt-in to "pre-release" or "early access" packages (I can't remember the name as they change it so often). Instead you could download the package directly here: https://www.nuget.org/packages/E.Deezer and then locally link to that verison of the library. 

Granted, there might be a load of API changes and breaks with that version so it might not be 100% drop-in replacement. If not, I'll see if I can do something to release another 4.X version with a fix.

**Comment by poirier-benoit** [comment]
Using the 5.0.0-beta1 version resolved the issue. I barely had any code written at this point, so it won't be an issue for me to use the beta. Thanks for the support!

**Comment by projectgoav** [comment]
Glad to hear it worked for you. Beta been out there for a while so I should probably submit a non-prerelease package to avoid others having the same problem. 

I'll close this issue off just now. Feel free to open a new one if you come across anything else!
